// AUTO-GENERATED by scripts/generateTenantIndex.ts — do not edit manually.
import type { AuthenticatedTemplate } from "../types";


const jsonTenants: Record<string, AuthenticatedTemplate> = {

};

export function getAuthenticatedTemplate(tenant: string): AuthenticatedTemplate | null {
  const fromJson = jsonTenants[tenant];
  if (fromJson) return fromJson;
  return null;
}
