// AUTO-GENERATED by scripts/generateTenantIndex.ts — do not edit manually.
import type { AuthenticatedTemplate } from "../types";
import acmePortalJson from "../../../configs/tenants/acme-portal.json";

const jsonTenants: Record<string, AuthenticatedTemplate> = {
  "acme-portal": acmePortalJson as AuthenticatedTemplate,
};

export function getAuthenticatedTemplate(tenant: string): AuthenticatedTemplate | null {
  const fromJson = jsonTenants[tenant];
  if (fromJson) return fromJson;
  return null;
}
