// AUTO-GENERATED by scripts/generateTenantIndex.ts — do not edit manually.
import type { AppTemplate } from "./types";
import { getInformationalTemplate } from "./informational";
import { getAuthenticatedTemplate } from "./authenticated";

export function getTemplate(tenant: string): AppTemplate {
  const auth = getAuthenticatedTemplate(tenant);
  if (auth) return auth;
  return getInformationalTemplate(tenant);
}
