// AUTO-GENERATED by scripts/generateTenantIndex.ts — do not edit manually.
import type { InformationalTemplate } from "../types";
import acmeDentalJson from "../../../configs/tenants/acme-dental.json";
import bobsBurgersJson from "../../../configs/tenants/bobs-burgers.json";
import mbgJson from "../../../configs/tenants/mbg.json";

const jsonTenants: Record<string, InformationalTemplate> = {
  "acme-dental": acmeDentalJson as InformationalTemplate,
  "bobs-burgers": bobsBurgersJson as InformationalTemplate,
  "mbg": mbgJson as InformationalTemplate,
};

export function getInformationalTemplate(tenant: string): InformationalTemplate {
  const fromJson = jsonTenants[tenant];
  if (fromJson) return fromJson;
  return jsonTenants["mbg"];
}
