// AUTO-GENERATED by scripts/generateTenantIndex.ts — do not edit manually.
import type { InformationalTemplate } from "../types";
import mbgJson from "../../../configs/tenants/mbg.json";

const jsonTenants: Record<string, InformationalTemplate> = {
  "mbg": mbgJson as InformationalTemplate,
};

export function getInformationalTemplate(tenant: string): InformationalTemplate {
  const fromJson = jsonTenants[tenant];
  if (fromJson) return fromJson;
  return jsonTenants["mbg"];
}
