// AUTO-GENERATED by scripts/generateTenantIndex.ts — do not edit manually.
import type { ContentTemplate } from "../types";


const jsonTenants: Record<string, ContentTemplate> = {

};

export function getContentTemplate(tenant: string): ContentTemplate | null {
  const fromJson = jsonTenants[tenant];
  if (fromJson) return fromJson;
  return null;
}
