// AUTO-GENERATED by scripts/generateTenantIndex.ts — do not edit manually.
import type { ContentTemplate } from "../types";
import sampleContentJson from "../../../configs/tenants/sample-content.json";

const jsonTenants: Record<string, ContentTemplate> = {
  "sample-content": sampleContentJson as ContentTemplate,
};

export function getContentTemplate(tenant: string): ContentTemplate | null {
  const fromJson = jsonTenants[tenant];
  if (fromJson) return fromJson;
  return null;
}
