// AUTO-GENERATED by scripts/generateTenantIndex.ts — do not edit manually.
import type { BookingTemplate } from "../types";
import sampleBookingJson from "../../../configs/tenants/sample-booking.json";

const jsonTenants: Record<string, BookingTemplate> = {
  "sample-booking": sampleBookingJson as BookingTemplate,
};

export function getBookingTemplate(tenant: string): BookingTemplate | null {
  const fromJson = jsonTenants[tenant];
  if (fromJson) return fromJson;
  return null;
}
