// AUTO-GENERATED by scripts/generateTenantIndex.ts — do not edit manually.
import type { BookingTemplate } from "../types";


const jsonTenants: Record<string, BookingTemplate> = {

};

export function getBookingTemplate(tenant: string): BookingTemplate | null {
  const fromJson = jsonTenants[tenant];
  if (fromJson) return fromJson;
  return null;
}
