// AUTO-GENERATED by scripts/generateTenantIndex.ts — do not edit manually.
import type { LoyaltyTemplate } from "../types";


const jsonTenants: Record<string, LoyaltyTemplate> = {

};

export function getLoyaltyTemplate(tenant: string): LoyaltyTemplate | null {
  const fromJson = jsonTenants[tenant];
  if (fromJson) return fromJson;
  return null;
}
