// AUTO-GENERATED by scripts/generateTenantIndex.ts — do not edit manually.
import type { LoyaltyTemplate } from "../types";
import sampleLoyaltyJson from "../../../configs/tenants/sample-loyalty.json";

const jsonTenants: Record<string, LoyaltyTemplate> = {
  "sample-loyalty": sampleLoyaltyJson as LoyaltyTemplate,
};

export function getLoyaltyTemplate(tenant: string): LoyaltyTemplate | null {
  const fromJson = jsonTenants[tenant];
  if (fromJson) return fromJson;
  return null;
}
