// AUTO-GENERATED by scripts/generateTenantIndex.ts — do not edit manually.
import type { CommerceTemplate } from "../types";
import sampleCommerceJson from "../../../configs/tenants/sample-commerce.json";

const jsonTenants: Record<string, CommerceTemplate> = {
  "sample-commerce": sampleCommerceJson as CommerceTemplate,
};

export function getCommerceTemplate(tenant: string): CommerceTemplate | null {
  const fromJson = jsonTenants[tenant];
  if (fromJson) return fromJson;
  return null;
}
