// AUTO-GENERATED by scripts/generateTenantIndex.ts — do not edit manually.
import type { CommerceTemplate } from "../types";


const jsonTenants: Record<string, CommerceTemplate> = {

};

export function getCommerceTemplate(tenant: string): CommerceTemplate | null {
  const fromJson = jsonTenants[tenant];
  if (fromJson) return fromJson;
  return null;
}
