/**
 * Auto-generates src/templates/informational/index.ts from configs/tenants/*.json.
 *
 * React Native / Metro requires static imports — we can't dynamically scan
 * at runtime. This script generates the import map so you never have to
 * manually register a tenant in the runtime loader.
 *
 * Run automatically as part of `npm run build:tenants`.
 */
import { readdirSync, writeFileSync } from "fs";
import { resolve, basename } from "path";

const tenantsDir = resolve(__dirname, "../configs/tenants");
const outFile = resolve(__dirname, "../src/templates/informational/index.ts");

function toCamelCase(id: string): string {
  return id.replace(/-([a-z])/g, (_m, chr) => chr.toUpperCase());
}

function main() {
  const files = readdirSync(tenantsDir)
    .filter((f) => f.endsWith(".json"))
    .sort();

  if (files.length === 0) {
    console.error("No tenant JSON files found in configs/tenants/");
    process.exit(1);
  }

  const imports: string[] = [];
  const entries: string[] = [];

  for (const file of files) {
    const tenantId = basename(file, ".json");
    const varName = toCamelCase(tenantId) + "Json";
    imports.push(
      `import ${varName} from "../../../configs/tenants/${tenantId}.json";`
    );
    entries.push(`  "${tenantId}": ${varName} as InformationalTemplate,`);
  }

  const source = `// AUTO-GENERATED by scripts/generateTenantIndex.ts — do not edit manually.
import type { InformationalTemplate } from "../types";
${imports.join("\n")}

const jsonTenants: Record<string, InformationalTemplate> = {
${entries.join("\n")}
};

export function getInformationalTemplate(tenant: string): InformationalTemplate {
  const fromJson = jsonTenants[tenant];
  if (fromJson) return fromJson;
  return jsonTenants.mbg;
}
`;

  writeFileSync(outFile, source, "utf8");
  // eslint-disable-next-line no-console
  console.log(`Generated ${outFile}`);
}

main();
