/**
 * Auto-generates template index files from configs/tenants/*.json.
 *
 * React Native / Metro requires static imports — we can't dynamically scan
 * at runtime. This script generates the import maps so you never have to
 * manually register a tenant in the runtime loader.
 *
 * Sorts tenants by templateId and generates:
 *   src/templates/<templateId>/index.ts  — per-type tenant resolver
 *   src/templates/index.ts               — unified resolver
 *
 * Run automatically as part of `npm run build:tenants`.
 */
import { readFileSync, readdirSync, writeFileSync, mkdirSync } from "fs";
import { resolve, basename } from "path";

const tenantsDir = resolve(__dirname, "../configs/tenants");
const templatesDir = resolve(__dirname, "../src/templates");

// All supported template types and their TypeScript type names
const TEMPLATE_TYPES: Record<string, { typeName: string; functionName: string; fallback: string | null }> = {
  informational: { typeName: "InformationalTemplate", functionName: "getInformationalTemplate", fallback: "mbg" },
  authenticated: { typeName: "AuthenticatedTemplate", functionName: "getAuthenticatedTemplate", fallback: null },
  booking: { typeName: "BookingTemplate", functionName: "getBookingTemplate", fallback: null },
  commerce: { typeName: "CommerceTemplate", functionName: "getCommerceTemplate", fallback: null },
  loyalty: { typeName: "LoyaltyTemplate", functionName: "getLoyaltyTemplate", fallback: null },
  content: { typeName: "ContentTemplate", functionName: "getContentTemplate", fallback: null },
  forms: { typeName: "FormsTemplate", functionName: "getFormsTemplate", fallback: null },
  directory: { typeName: "DirectoryTemplate", functionName: "getDirectoryTemplate", fallback: null },
};

type TenantEntry = { id: string; varName: string };

function toCamelCase(id: string): string {
  return id.replace(/-([a-z])/g, (_m, chr) => chr.toUpperCase());
}

function main() {
  const files = readdirSync(tenantsDir)
    .filter((f) => f.endsWith(".json"))
    .sort();

  if (files.length === 0) {
    console.error("No tenant JSON files found in configs/tenants/");
    process.exit(1);
  }

  // Sort tenants into buckets by templateId
  const buckets: Record<string, TenantEntry[]> = {};
  for (const key of Object.keys(TEMPLATE_TYPES)) {
    buckets[key] = [];
  }

  for (const file of files) {
    const tenantId = basename(file, ".json");
    const varName = toCamelCase(tenantId) + "Json";
    const json = JSON.parse(readFileSync(resolve(tenantsDir, file), "utf8"));
    const templateId = json.templateId ?? "informational";

    if (!buckets[templateId]) {
      console.warn(`Unknown templateId "${templateId}" in ${file}, skipping.`);
      continue;
    }
    buckets[templateId].push({ id: tenantId, varName });
  }

  // Generate per-type index files
  for (const [templateId, config] of Object.entries(TEMPLATE_TYPES)) {
    const dir = resolve(templatesDir, templateId);
    mkdirSync(dir, { recursive: true });

    generateIndex({
      entries: buckets[templateId],
      typeName: config.typeName,
      functionName: config.functionName,
      outFile: resolve(dir, "index.ts"),
      importDepth: "../../../",
      fallback: config.fallback,
    });
  }

  // Generate unified resolver
  generateUnifiedIndex();
}

function generateIndex(opts: {
  entries: TenantEntry[];
  typeName: string;
  functionName: string;
  outFile: string;
  importDepth: string;
  fallback: string | null;
}) {
  const imports = opts.entries.map(
    (e) => `import ${e.varName} from "${opts.importDepth}configs/tenants/${e.id}.json";`
  );

  const mapEntries = opts.entries.map(
    (e) => `  "${e.id}": ${e.varName} as ${opts.typeName},`
  );

  const returnType = opts.fallback ? opts.typeName : `${opts.typeName} | null`;
  const fallbackLine = opts.fallback
    ? `  return jsonTenants["${opts.fallback}"];`
    : `  return null;`;

  const source = `// AUTO-GENERATED by scripts/generateTenantIndex.ts — do not edit manually.
import type { ${opts.typeName} } from "../types";
${imports.join("\n")}

const jsonTenants: Record<string, ${opts.typeName}> = {
${mapEntries.join("\n")}
};

export function ${opts.functionName}(tenant: string): ${returnType} {
  const fromJson = jsonTenants[tenant];
  if (fromJson) return fromJson;
${fallbackLine}
}
`;

  writeFileSync(opts.outFile, source, "utf8");
  console.log(`Generated ${opts.outFile}`);
}

function generateUnifiedIndex() {
  const getters = Object.entries(TEMPLATE_TYPES)
    .filter(([id]) => id !== "informational") // informational is the fallback
    .map(([, config]) => `    ${config.functionName},`);

  const imports = Object.entries(TEMPLATE_TYPES).map(
    ([id, config]) => `import { ${config.functionName} } from "./${id}";`
  );

  const source = `// AUTO-GENERATED by scripts/generateTenantIndex.ts — do not edit manually.
import type { AppTemplate } from "./types";
${imports.join("\n")}

export function getTemplate(tenant: string): AppTemplate {
  for (const getter of [
${getters.join("\n")}
  ]) {
    const t = getter(tenant);
    if (t) return t;
  }
  return getInformationalTemplate(tenant);
}
`;

  const outFile = resolve(templatesDir, "index.ts");
  writeFileSync(outFile, source, "utf8");
  console.log(`Generated ${outFile}`);
}

main();
