/**
 * Auto-generates template index files from configs/tenants/*.json.
 *
 * React Native / Metro requires static imports — we can't dynamically scan
 * at runtime. This script generates the import maps so you never have to
 * manually register a tenant in the runtime loader.
 *
 * Outputs:
 *   src/templates/informational/index.ts  — informational tenant resolver
 *   src/templates/authenticated/index.ts  — authenticated tenant resolver
 *   src/templates/index.ts                — unified resolver
 *
 * Run automatically as part of `npm run build:tenants`.
 */
import { readFileSync, readdirSync, writeFileSync, mkdirSync } from "fs";
import { resolve, basename } from "path";

const tenantsDir = resolve(__dirname, "../configs/tenants");
const templatesDir = resolve(__dirname, "../src/templates");

function toCamelCase(id: string): string {
  return id.replace(/-([a-z])/g, (_m, chr) => chr.toUpperCase());
}

type TenantEntry = { id: string; varName: string };

function main() {
  const files = readdirSync(tenantsDir)
    .filter((f) => f.endsWith(".json"))
    .sort();

  if (files.length === 0) {
    console.error("No tenant JSON files found in configs/tenants/");
    process.exit(1);
  }

  const informational: TenantEntry[] = [];
  const authenticated: TenantEntry[] = [];

  for (const file of files) {
    const tenantId = basename(file, ".json");
    const varName = toCamelCase(tenantId) + "Json";
    const json = JSON.parse(readFileSync(resolve(tenantsDir, file), "utf8"));

    if (json.templateId === "authenticated") {
      authenticated.push({ id: tenantId, varName });
    } else {
      informational.push({ id: tenantId, varName });
    }
  }

  // Generate informational/index.ts
  generateIndex({
    entries: informational,
    typeName: "InformationalTemplate",
    functionName: "getInformationalTemplate",
    outFile: resolve(templatesDir, "informational/index.ts"),
    importDepth: "../../../",
    fallback: "mbg",
  });

  // Generate authenticated/index.ts
  mkdirSync(resolve(templatesDir, "authenticated"), { recursive: true });
  generateIndex({
    entries: authenticated,
    typeName: "AuthenticatedTemplate",
    functionName: "getAuthenticatedTemplate",
    outFile: resolve(templatesDir, "authenticated/index.ts"),
    importDepth: "../../../",
    fallback: null,
  });

  // Generate unified src/templates/index.ts
  generateUnifiedIndex();
}

function generateIndex(opts: {
  entries: TenantEntry[];
  typeName: string;
  functionName: string;
  outFile: string;
  importDepth: string;
  fallback: string | null;
}) {
  const imports = opts.entries.map(
    (e) => `import ${e.varName} from "${opts.importDepth}configs/tenants/${e.id}.json";`
  );

  const mapEntries = opts.entries.map(
    (e) => `  "${e.id}": ${e.varName} as ${opts.typeName},`
  );

  const returnType = opts.fallback ? opts.typeName : `${opts.typeName} | null`;
  const fallbackLine = opts.fallback
    ? `  return jsonTenants["${opts.fallback}"];`
    : `  return null;`;

  const source = `// AUTO-GENERATED by scripts/generateTenantIndex.ts — do not edit manually.
import type { ${opts.typeName} } from "../types";
${imports.join("\n")}

const jsonTenants: Record<string, ${opts.typeName}> = {
${mapEntries.join("\n")}
};

export function ${opts.functionName}(tenant: string): ${returnType} {
  const fromJson = jsonTenants[tenant];
  if (fromJson) return fromJson;
${fallbackLine}
}
`;

  writeFileSync(opts.outFile, source, "utf8");
  console.log(`Generated ${opts.outFile}`);
}

function generateUnifiedIndex() {
  const source = `// AUTO-GENERATED by scripts/generateTenantIndex.ts — do not edit manually.
import type { AppTemplate } from "./types";
import { getInformationalTemplate } from "./informational";
import { getAuthenticatedTemplate } from "./authenticated";

export function getTemplate(tenant: string): AppTemplate {
  const auth = getAuthenticatedTemplate(tenant);
  if (auth) return auth;
  return getInformationalTemplate(tenant);
}
`;

  const outFile = resolve(templatesDir, "index.ts");
  writeFileSync(outFile, source, "utf8");
  console.log(`Generated ${outFile}`);
}

main();
