// AUTO-GENERATED by scripts/generateTenantIndex.ts — do not edit manually.
import type { FormsTemplate } from "../types";


const jsonTenants: Record<string, FormsTemplate> = {

};

export function getFormsTemplate(tenant: string): FormsTemplate | null {
  const fromJson = jsonTenants[tenant];
  if (fromJson) return fromJson;
  return null;
}
