// AUTO-GENERATED by scripts/generateTenantIndex.ts — do not edit manually.
import type { FormsTemplate } from "../types";
import sampleFormsJson from "../../../configs/tenants/sample-forms.json";

const jsonTenants: Record<string, FormsTemplate> = {
  "sample-forms": sampleFormsJson as FormsTemplate,
};

export function getFormsTemplate(tenant: string): FormsTemplate | null {
  const fromJson = jsonTenants[tenant];
  if (fromJson) return fromJson;
  return null;
}
