name: Preview build (tenant)

on:
  workflow_dispatch:
    inputs:
      tenant:
        type: string
        required: true
      version:
        type: string
        required: false
        default: "1.0.0"

jobs:
  prepare:
    steps:
      - uses: eas/checkout
      - uses: eas/install_node_modules

      - name: Build and validate tenant configs
        run: |
          npm run build:tenants
          npm run validate:tenants

  build_android:
    needs: [prepare]
    type: build
    params:
      platform: android
      profile: preview
    env:
      APP_TENANT: ${{ inputs.tenant }}
      NATIVE_ID_MODE_ANDROID: tenant
      NATIVE_ID_MODE_IOS: shared
      APP_VERSION: ${{ inputs.version }}

  build_ios:
    needs: [prepare]
    type: build
    params:
      platform: ios
      profile: preview
    env:
      APP_TENANT: ${{ inputs.tenant }}
      NATIVE_ID_MODE_ANDROID: tenant
      NATIVE_ID_MODE_IOS: shared
      APP_VERSION: ${{ inputs.version }}
