// AUTO-GENERATED by scripts/generateTenantIndex.ts — do not edit manually.
import type { DirectoryTemplate } from "../types";


const jsonTenants: Record<string, DirectoryTemplate> = {

};

export function getDirectoryTemplate(tenant: string): DirectoryTemplate | null {
  const fromJson = jsonTenants[tenant];
  if (fromJson) return fromJson;
  return null;
}
