// AUTO-GENERATED by scripts/generateTenantIndex.ts — do not edit manually.
import type { DirectoryTemplate } from "../types";
import sampleDirectoryJson from "../../../configs/tenants/sample-directory.json";

const jsonTenants: Record<string, DirectoryTemplate> = {
  "sample-directory": sampleDirectoryJson as DirectoryTemplate,
};

export function getDirectoryTemplate(tenant: string): DirectoryTemplate | null {
  const fromJson = jsonTenants[tenant];
  if (fromJson) return fromJson;
  return null;
}
